"""empty message

Revision ID: 08faad1af355
Revises: 78e752978480
Create Date: 2025-04-24 02:57:55.034391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08faad1af355'
down_revision = '78e752978480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
