"""empty message

Revision ID: 223621c416c2
Revises: a8d7813926b1
Create Date: 2025-04-25 02:04:49.555772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223621c416c2'
down_revision = 'a8d7813926b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duracion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.drop_column('duracion')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
