"""empty message

Revision ID: 76439b925d17
Revises: c22c04de0fd8
Create Date: 2025-05-09 13:19:07.468470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76439b925d17'
down_revision = 'c22c04de0fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
