"""empty message

Revision ID: a8d7813926b1
Revises: 08faad1af355
Create Date: 2025-04-25 02:01:46.767507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d7813926b1'
down_revision = '08faad1af355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historia_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favoritos_categoria_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'historias', ['historia_id'], ['id'])
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_categoria_id_fkey', 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('historia_id')

    # ### end Alembic commands ###
